apiVersion: v1
kind: Service
metadata:
  labels:
    app: wireguard
  name: wireguard
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31337
    port: 9999
    protocol: UDP
    targetPort: 9999
  selector:
    app: wireguard
  sessionAffinity: None
  type: LoadBalancer
